<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="THSLT10735" failures="1" tests="10" name="Surefire test" time="16.409" errors="0" timestamp="2025-04-10T19:21:10 IST">
  <testcase classname="api.test.DDTests" name="testPostUser" time="4.038"/>
  <testcase classname="api.test.DDTests" name="testPostUser" time="1.045"/>
  <testcase classname="api.test.DDTests" name="testPostUser" time="1.061"/>
  <testcase classname="api.test.DDTests" name="testDeleteUserByName" time="1.114"/>
  <testcase classname="api.test.DDTests" name="testDeleteUserByName" time="1.066"/>
  <testcase classname="api.test.DDTests" name="testDeleteUserByName" time="1.0"/>
  <testcase classname="api.test.UserTests" name="testpostuser" time="1.124"/>
  <testcase classname="api.test.UserTests" name="testgetuser" time="1.237">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests.testgetuser(UserTests.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- testgetuser -->
  <testcase classname="api.test.UserTests" name="testupdateUserByName" time="2.189"/>
  <testcase classname="api.test.UserTests" name="deleteuserByName" time="1.093"/>
</testsuite> <!-- Surefire test -->
